service: serverless-with-conditional-resources

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

custom:
  functions:
    dev: false
    prod:
      hello:
        handler: handler.main
        events:
          - http:
              path: /
              method: get

functions: ${self:custom.functions.${opt:stage}}

